Set max ammo for Bouncy and fire ammo types
Juansero29/SFDScripts pull request #45
Opened 2021-03-21 16:14 UTC by GenericUsername27

Fixes Issue #44.

![BouncyMaxAmmo](https://user-images.githubusercontent.com/76974284/111911881-8e623f00-8a67-11eb-8a58-53772f543797.gif)

Secondary weapons get one clip, except for flaregun (2 shots)

There are some irregularities in the amount of ammo for primary weapons: I didn't want to do separate if statements for bow, grenade launcher, m60 and bazooka, so I set it to 1/4 of max ammo, rounded up. A few guns have slightly more than one clip, if you want me to even it out just let me know.

Since all guns can have 3 or more clips, choosing fire/bouncy ammo gives you an extra clip, so I reduced the cost of both by just 100.

2021-03-21 18:56 UTC, Juansero29 requested changes
I'm OK with the new calculations, only feedback is on code formatting so that this code gets divided into smaller methods/functions and thus is easier tor read

2021-03-21 18:56 UTC, Juansero29 commented on SFDScripts/Internal/Hardcore/Hardcore.cs
> +                            int ammo = (int)Math.Ceiling(((double)first.MaxTotalAmmo / 4));
Could you refactor this into smaller methods? For example methods called `CalculateBouncyAmmoForPrimaryWeapon` and then `CalculateBouncyAmmoForSecondaryWeapon`

2021-03-21 18:56 UTC, Juansero29 commented on SFDScripts/Internal/Hardcore/Hardcore.cs
> +                            pl.GiveWeaponItem(first.WeaponItem);
Same here

2021-03-24 14:20 UTC, GenericUsername27 commented
Alright, I made a big mess of things, but I think it's all good now.
Let me know if you want me to break it down into even smaller parts, and how, cause I don't see how to sensibly do so.

2021-03-26 00:11 UTC, Juansero29 reviewed
Maybe some little refactoring to do, but I'll do it later :)

2021-03-26 00:11 UTC, merged

2021-03-26 00:12 UTC, Juansero29 commented
Fixes #45